runtime: ruby25

entrypoint: bundle exec rackup -s Puma -p $PORT

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 1
  min_idle_instances: 0
  max_idle_instances: 0
  max_concurrent_requests: 80
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  min_pending_latency: 15000ms
  max_pending_latency: 15000ms
