default: &default
  title: Doorkeeperのイベント

  groups:
    - 74284f630e710a7c63f8599d5f # 銀座Rails
    - asakusarb
    - f60d71ff61dfbe61b1ce22791b # TX.rb
    - ginzarb
    - growrb
    - guruby
    - hmrb
    - koberb
    - kyotorb
    - kzrb
    - machidarb
    - matsue-rb
    - mitakarb
    - naniwarb
    - nishinipporirb
    - nishishinjuku
    - nishiwaki-koberb
    - okinawarb
    - rails-follow-up-kobe
    - rails-follow-up-kyoto
    - rails-follow-up-osaka
    - ruby-tuesday
    - rubykansai
    - rubytokai
    - sendagayarb
    - shibuyarb
    - shinosakarb
    - tokyu-rubykaigi
    - tokyurb
    - toruby
    - trbmeetup
    - wakayamarb
    - yokohamarb

test:
  <<: *default

  groups:
    - shibuyarb

development:
  <<: *default

production:
  <<: *default
